# Generated by Django 5.1.4 on 2024-12-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="qr_code_image",
            field=models.ImageField(blank=True, null=True, upload_to="qr_codes/"),
        ),
    ]
