# Generated by Django 5.1.4 on 2024-12-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demons", "0003_alter_qrcode_code_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="code_id",
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
