# Generated by Django 5.1.4 on 2024-12-14 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demons", "0004_alter_qrcode_code_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="qr_code",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="demons.qrcode",
            ),
        ),
        migrations.AlterField(
            model_name="tempvisitor",
            name="qr_code",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="demons.qrcode"
            ),
        ),
        migrations.AlterField(
            model_name="tempvisitor",
            name="time_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
