# Generated by Django 5.1.4 on 2024-12-14 03:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demons", "0005_visitor_qr_code_alter_tempvisitor_qr_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tempvisitor",
            name="registered_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="qr_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="demons.qrcode",
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="time_in",
            field=models.DateTimeField(),
        ),
    ]
