# Generated by Django 5.1.4 on 2024-12-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demons", "0007_alter_visitor_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AddField(
            model_name="student",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
    ]
